Update Makefile semantics

diff --git a/tools/c_api_binary/Makefile b/tools/c_api_binary/Makefile
--- a/tools/c_api_binary/Makefile
+++ b/tools/c_api_binary/Makefile
@@ -17,20 +17,22 @@ ifeq ($(OS), Darwin)
 endif
 
 check:
-	if [ ! -d "$(INCLUDE_DIR)" ]; then \
-			echo "$(INCLUDE_DIR) does not exist, cancelling..."; \
-			exit 1; \
+	@if [ ! -d "$(INCLUDE_DIR)" ]; then \
+		echo "INCLUDE_DIR=$(INCLUDE_DIR) does not exist, cannot install qiskit-c-api. "; \
+		echo "To use a custom include directory, run `make install INCLUDE_DIR=\"</path/to/include/dir>\"`"
+		echo "Exiting..."; \
+		exit 1; \
 	fi
-	if [ ! -d "$(LIB_DIR)" ]; then \
-			echo "$(LIB_DIR) does not exist, cancelling..."; \
-			exit 1; \
+	@if [ ! -d "$(LIB_DIR)" ]; then \
+		echo "LIB_DIR=$(LIB_DIR) does not exist, cannot install qiskit-c-api. Exiting..."; \
+		echo "To use a custom lib directory, run `make install LIB_DIR=\"</path/to/lib/dir>\"`"
+		exit 1; \
 	fi
-
-install:
+install: check
 	cp dist/c/include/qiskit.h $(INCLUDE_DIR)
-	cp -r dist/c/include/qiskit/ $(INCLUDE_DIR)
-	cp dist/c/lib/libqiskit.so $(LIB_DIR)
+	cp -r dist/c/include/qiskit $(INCLUDE_DIR)
+	cp dist/c/lib/libqiskit.* $(LIB_DIR)
 uninstall:
 	rm -f $(INCLUDE_DIR)/qiskit.h
-	rm -rf $(INCLUDE_DIR)/qiskit/
-	rm -rf $(LIB_DIR)/libqiskit.so
+	rm -rf $(INCLUDE_DIR)/qiskit
+	rm -f $(LIB_DIR)/libqiskit.so
