Preload Aer's `libgomp`
As explained in the code comment, I don't fully understand _why_ this
suddenly fails to load, but I'd prefer to get onto the `ubuntu-26.04`
image as soon as possible (before the 2026-10-19 auto-switch date)
without losing coverage that Aer provided.

We can figure out what the root cause of this new error is later; it may
require changes in Aer, or a larger re-working of the import order in
Qiskit.

diff --git a/.github/workflows/test-linux.yml b/.github/workflows/test-linux.yml
--- a/.github/workflows/test-linux.yml
+++ b/.github/workflows/test-linux.yml
@@ -91,6 +91,7 @@ jobs:
             -c constraints.txt \
             --group test \
             -e .
+
       - name: Install Optional packages
         run: |
           set -e
@@ -98,6 +99,21 @@ jobs:
           python -m pip install --group optionals-all -c constraints.txt
           python -m pip check
         if: ${{ inputs.install-optionals }}
+
+      - name: Preload libgomp for Aer
+        # TODO: As of the Ubuntu 26.04, Aer has been failing to load with a message
+        #   libgomp-a34b3233.so.1.0.0: cannot allocate memory in static TLS block
+        # This appears to be something to do with initialisation order.  In order to keep the Aer
+        # tests unskipped, this finds Aer's bundled `libgomp`, so the test runners can forcibly load
+        # it up.
+        run: |
+          set -e
+          source test-job/bin/activate
+          libgomp=$(python -c 'from importlib.metadata import files; print(next(str(f.locate()) for f in files("qiskit_aer") if "libgomp" in str(f)))')
+          echo "libgomp=$libgomp"
+          echo "AER_LIBGOMP=$libgomp" >> "$GITHUB_ENV"
+        if: ${{ inputs.install-optionals }}
+
       - name: Install optional non-Python dependencies
         run: sudo tools/install_ubuntu_graphviz.sh
         if: ${{ inputs.install-optionals }}
@@ -114,6 +130,7 @@ jobs:
           QISKIT_PARALLEL: FALSE
           QISKIT_IGNORE_USER_SETTINGS: TRUE
           RUST_BACKTRACE: 1
+          LD_PRELOAD: ${{ env.LD_PRELOAD }}:${{ env.AER_LIBGOMP }}
       - name: Filter stestr history
         if: ${{ !inputs.install-from-sdist }}
         run: |
@@ -137,6 +154,7 @@ jobs:
           QISKIT_PARALLEL: FALSE
           QISKIT_IGNORE_USER_SETTINGS: TRUE
           RUST_BACKTRACE: 1
+          LD_PRELOAD: ${{ env.LD_PRELOAD }}:${{ env.AER_LIBGOMP }}
       - name: Filter stestr history (sdist)
         if: ${{ inputs.install-from-sdist }}
         run: |
